spring.mvc.view:
  prefix: '/WEB-INF/view/'
  suffix: '.jsp'

shop:
  properties:
    products:
      - product:
        id: 0
        name: 'Product1'
        price: 50.0
      - product:
        id: 1
        name: 'Product2'
        price: 60.0
      - product:
        id: 2
        name: 'Product3'
        price: 70.0